### ISSUE TITLE
Module parse failed

### ISSUE THREAD

**Issue by qinfp123** [hiyali/vue-smooth-picker#1]
After installing the plug-in on my own project, I create a new.Vue page，  
 import 'vue-smooth-picker/dist/css/style.css'
 import { SmoothPicker } from 'vue-smooth-picker' 
command line error said module parsing failed，
 import 'vue-smooth-picker/dist/css/style.css' If you annotate it, the page can start the preview normally, but the console is wrong， e.removeEventListener is not a function

**Comment by hiyali** [comment]
@qinfp123 Thanks for your feedback. And it looks like your css-loader or css-loader configuration's fault, Can you try import css file by another css?

In fact, you can solve above issue with [these webpack configurations](https://github.com/hiyali/vue-smooth-picker/blob/gh-pages/conf/webpack.conf.js#L66-L67).

**Comment by hiyali** [comment]
@qinfp123  I update [example gender](https://hiyali.github.io/vue-smooth-picker/example/gender/) with your way, you can see it in [this line](https://github.com/hiyali/vue-smooth-picker/blob/gh-pages/example/gender/index.js#L4).

Now i have to close this issue, you can reopen this issue that if still with same problem.
