### ISSUE TITLE
Adding chevron icon and onclick functionality on it

### ISSUE THREAD

**Issue by rassemdev** [hiyali/vue-smooth-picker#10]
hi @hiyali 
Isn't it more user friendly to add up/down chevron icon instead of directly clicking on the value? Or is there any way to add it? like the image below!
![image](https://user-images.githubusercontent.com/34296924/38023973-7750c8a8-32a5-11e8-9a15-6e84659fae84.png)

**Comment by hiyali** [comment]
Hi there, I don't think above opinion is a more friendly way.
But, You can do it by yourself like(NOT EQUAL) below:
```javascript
  const movedIndex = pickerInst.currentIndexList[gIndex] +/- 1
  pickerInst.$set(pickerInst.currentIndexList, gIndex, movedIndex)
  pickerInst.correctionCurrentIndex(null, gIndex)
```

**Comment by hiyali** [comment]
So @rassemdev , shall we close this issue?

**Comment by rassemdev** [comment]
I really couldn't figure it out how to do it. But yeah u can close it
