### ISSUE TITLE
Configurable Number of Previous/Next Values

### ISSUE THREAD

**Issue by changhao** [hiyali/vue-smooth-picker#11]
@hiyali @action-hong  
First of all, thank all the authors/contributors for your effort to make this picker happen. Really great to use!

I'd like to request an enhancement, if possible.

**Current Situation:** The picker displays 2 previous values and 2 next values, as below,
```
      previous previous value
      previous value
      [current value]
      next value
      next next value
```

**Problem:** In one of my application, this above display just took too much **vertical** space.

**Ask:** Is it possible to make previous/next value counts configurable? For instance, if I set the count to "1", the picker shall display as below,
```
      previous value
      [current value]
      next value
```

Could you implement this feature, please?

Thank you very much in advance.

Best regards,
Changhao

**Comment by hiyali** [comment]
@changhao Thank you very much for your feedback.

I will consider this feature as soon as possible, but now you can use below style code to override picker css to fix your problem.
```css
.smooth-picker {
  height: 6em;
}
.smooth-picker .smooth-list {
  top: 2em;
}
```

**Comment by changhao** [comment]
@hiyali  
Hi Hiyali, it works. Thank you so much.

**Comment by hiyali** [comment]
@changhao You're welcome.

**Comment by sreegopi** [comment]
@hiyali @action-hong,
I'd like to request an enhancement, if possible.
Current UI: The picker displays 2 previous values and 2 next values, as below,
i want to show more items previous 10 and next also 10 values(.smooth-picker {
  height: 100vh;
}
not working

**Comment by hiyali** [comment]
Hi, @sreegopi . It won't work like that at the current (or previous) release.
But you can change the source code to do that. I have no time to implement this kind of feature and welcome to PR, Thank you.

**Comment by sreegopi** [comment]
Thank you for quick replay @hiyali, i will try to change the code accordingly. If possible give a suggestion which method i need to change.

**Comment by hiyali** [comment]
@sreegopi The `getItemStyle` method is the key and must change the CSS.

The result that returned in `if (Math.abs(gapCount) < 4) {...}` is the style of the items that showing. other returns are for the hidden elements.

**Comment by sreegopi** [comment]
Thank you @hiyali, i will change the things accordingly.
