### ISSUE TITLE
动态设置数据时样式出现问题

### ISSUE THREAD

**Issue by ZYSHINee** [hiyali/vue-smooth-picker#12]
我在使用上分为月份 和  日期两列，当我切换月份时，对应的日期我动态设置了只有一天，且有设置日期这列的当前值为这个唯一值，但是，这个时候这个唯一值跑到外层容器之外，导致无法显示，滑动之后才会正常显示
`// 生成dateSlots数组中的日期values值
        createDay(endDay, startDay = 0) {
            const me = this;
            me.dateSlots[1].list = []; // 清空dateSlots数组中的values日期值
            for (let i = startDay; i < endDay; i++) {
                if (i < 9) {
                    me.dateSlots[1].list.push(`0${+i + 1}号`);
                } else {
                    me.dateSlots[1].list.push(`${+i + 1}号`);
                }
            }
        }`

**Comment by hiyali** [comment]
@ZYSHINee 非常感谢你的反馈。

首先没有看懂你具体要实现什么，然后你给出的例子中 markdown 里展示的代码需要优化显示。像这样
```javascript
// 生成dateSlots数组中的日期values值
createDay(endDay, startDay = 0) { 
  const me = this; me.dateSlots[1].list = []; // 清空dateSlots数组中的values日期值 
  for (let i = startDay; i < endDay; i++) { 
    if (i < 9) { 
      me.dateSlots[1].list.push(0${+i + 1}号);
    } else { 
      me.dateSlots[1].list.push(${+i + 1}号); 
    } 
  } 
}
```
这样可以节省给你写答案的人的阅读时间。

补充：你先可以检查一下此picker的 [date-time 例子](https://hiyali.github.io/vue-smooth-picker/example/datetime/)，如果是你要的类型的话，可以参考[例子的代码](https://github.com/hiyali/vue-smooth-picker/blob/gh-pages/example/datetime/index.vue)。

**Comment by ZYSHINee** [comment]
ok ，不好意思

**Comment by ZYSHINee** [comment]
其实我的问题就是，按date-time的例子，当我切换年份的时候，我希望月份这列能动态地根据我选择的年份而切换，而不是切换年份时，月份的选中项还是保持不变

**Comment by ZYSHINee** [comment]
因为我的业务逻辑是：当前日期往回计算30天，假设当前日期是5月30日，那么我的可选日期就是从4月30日到5月30日，假设day这一列选中30，但当我切换到4月份时，day这列还是在30号这个位置，但是实际的位置却在这列的最上方，没有对应显示

**Comment by hiyali** [comment]
明白了，应该是与 #13 问题相同，鉴于此问题比较突出，刚更新了插件，并修复了此问题，可以更新 smooth picker 版本至 0.3.8 后再试。如果问题还是没有得到解决，可以重新打开此 issue。

**Comment by ZYSHINee** [comment]
好的，问题已解决，感谢！




发自网易邮箱大师
在2018年5月31日 13:30，Salam Hiyali<notifications@github.com> 写道：

Closed #12.

**Comment by ZYSHINee** [comment]
依赖问题？




发自网易邮箱大师
在2018年5月31日 13:30，Salam Hiyali<notifications@github.com> 写道：

Closed #12.
