### ISSUE TITLE
使用 setGroupData() 更新 currentIndex 后，DOM上的显示的值无法马上刷新

### ISSUE THREAD

**Issue by puerdon** [hiyali/vue-smooth-picker#13]
**范例源码连结**
[https://codepen.io/puerdon/pen/QxwJdZ?editors=1010](url)

**使用套件**
Vue, Vuetify, vue-smooth-picker

**预期行为**
使用者点击data-table中的时间"HHMM"后，下方跳出bottom sheet，然后将 bottom sheet 中的 vue-smooth-picker 的小时滚轴显示为 HH，分钟滚轴显示为 MM。 

**实际发生行为**
bottom sheet出现后，vue-smooth-picker的小时滚轴以及分钟滚轴仍然显示为初始 `currentIndex` 设定值 0。使用者必须在 vue-smooth-picker 上面点击一下，滚轴的值才会变成预期的HH和MM。

**目前实作方法**
1. 使用者点击data tabale中的时间时，呼叫 `edit()`
2. 算出时间字串的小时与分钟，并分别转换成 Int 型态的变数 `hour` 和 `minute`
3. 在 `edit()` 中，以 `smoothPicker.setGroupData()` 去把两个滚轴的 `currentIndex` `更新成步骤2的`hour`和`minute`
4. 实际以 `console.log(smoothPicker.GetCurrentIndexList())` 测试，可以发现呼叫`edit()` 之后，的确有成功改变 `currentIndex` 的值，只是 DOM 上的值没有马上改变，必须使用者点击一下后才会刷新。

**讨论**
再看过Issue list后，不确定是否与 `Vue.nextTick()` 有关。希望可以寻求作者的协助，看看我在作法上哪边出了问题。

感謝！

**Comment by hiyali** [comment]
@puerdon 非常感谢你的反馈。

代码看了，这个问题是因为 picker 的 dom 没有刷新。vue 认为它的数据没有更新，所以就没有重新渲染dom，直到你按了一次。

如果只是按照这个逻辑想让它正常工作，加上一个 key 属性，就可以刷新 dom 了。
```javascript
<smooth-picker :key="show_bottom" ref="smoothPicker" :data="picker_data" />
```

**Comment by hiyali** [comment]
刚升级了 picker 到 0.3.8，修复了你遇到的问题。

codepen 中的插件版本换成 0.3.8 就可以及时刷新了（不用 key 属性）。清理缓存后，我这边在codepen 上测试通过，如果问题还是没有被修复可以重新打开此 issue。

**Comment by puerdon** [comment]
@hiyali 感谢作者的回复，试了加上 `:key` 的方式，也试了更新至 0.3.8 版，都可以如预期运作了。謝了！
