### ISSUE TITLE
请问要怎样在中间添加字体？

### ISSUE THREAD

**Issue by Gerogina6** [hiyali/vue-smooth-picker#16]
例如：
_____1__________1_________
_____2 小时_____2 分钟___
_____3__________3_________
然后让小时和分钟固定在那里，就选择前面的数字这样。
谢谢！

**Comment by hiyali** [comment]
@Georginaaaa 可以参考例子：[Product 的代码](https://github.com/hiyali/vue-smooth-picker/blob/gh-pages/example/product/index.vue)。在你的例子中，只需把下标为1和3的data子项设成
```javascript
{
  divider: true,
  text: "小时" // 或 分钟
}
```
即可。

我就顺手关闭该问题了，如果没能如愿得到以上效果，可以重新打开此issue继续提问，谢谢。
