### ISSUE TITLE
scroll bug

### ISSUE THREAD

**Issue by jacklovepdf** [hiyali/vue-smooth-picker#17]
when change the length of the data ,the scroll of picker is not work!

**Comment by jacklovepdf** [comment]
I have solved this problem by the following method:
`
                        setTimeout(() => {
                            self.$refs.smoothPicker.getGroupsRectList();
                        },0);
`

**Comment by hiyali** [comment]
Can I see your example of this issue online? please. @jacklovepdf

**Comment by hiyali** [comment]
I'll close this issue if you can't tell me more. @jacklovepdf
