### ISSUE TITLE
Chrome error when touch

### ISSUE THREAD

**Issue by lerous** [hiyali/vue-smooth-picker#19]
[Chrome Dev Tools - Mobile] Unable to preventDefault inside passive event listener due to target being treated as passive.

**Comment by hiyali** [comment]
Thank you for your feedback.

Upgrade vue-smooth-picker to 0.4.2 `npm i -S vue-smooth-picker@0.4.2` and retry.
Open this issue if the error still exists.

**Comment by lerous** [comment]
the bug is still exist, and the date mode in 4.0 works fine and now it went wrong :(

**Comment by hiyali** [comment]
@lerous well, then could you give me more information about this issue? like online code.

**Comment by echooohce** [comment]
i can't slide it when don't add the key, but if add the key , it can slide, but it will stop at the default value.

**Comment by hiyali** [comment]
If you can't tell me more, I'll close this issue.

Because the problem may not exist. show me your code that occurred this issue OR send a pull request for fix this.

Thanks a lot.
