### ISSUE TITLE
TypeError:e.removeEventListener is not a function in weex-toolkit project

### ISSUE THREAD

**Issue by qinfp123** [hiyali/vue-smooth-picker#2]
1.)  将插件npm i -S vue-smooth-picker 安装在我的项目
2.) 在页面import 'vue-smooth-picker/dist/css/style.css' 、import SmoothPicker from 'vue-smooth-picker' 、
      Vue.use(SmoothPicker)
3.) webpack.config.js配置 module: {
            rules: [
                {
                    test: /\.js$/,
                    loader: 'babel-loader',
                    exclude: /node_modules/
                }, {
                    test: /\.vue(\?[^?]+)?$/,
                    loaders: []
                },
                {
                    test: /\.css$/,
                      loader: 'style-loader!css-loader!stylus-loader',
                },
            ],

        }
4.) 预览页面，报错e.removeEventListener is not a function

**Comment by hiyali** [comment]
@qinfp123 非常感谢你的反馈。

1. 在用什么操作系统、版本？
2. 哪个浏览器、版本？
3. Vuejs 是哪个版本?

或者 发一下 QQ，我远程协助你看看到底发生了什么。

附：如果你能正常使用[这个示例](https://hiyali.github.io/vue-smooth-picker/example/gender/)，应该可以确定 vue-smooth-picker 没有问题。

**Comment by qinfp123** [comment]
1.）用的window10
2.）谷歌浏览器 版本 60.0.3095.5
3.）vue.js版本2.0
4.）284664948 我的QQ
5.）不能正常使用示例，页面显示空白，控制台报错e.removeEventListener is not a function

**Comment by hiyali** [comment]
@qinfp123 
你用的是 weex-toolkit 生成的工程，而这个工程引用的是 phantom-limb 这个库，很抱歉，vue-smooth-picker 暂时无法支持在这种环境下正常工作。
