### ISSUE TITLE
Chrome error touchend event

### ISSUE THREAD

**Issue by andrewj-bjss** [hiyali/vue-smooth-picker#20]
smooth-picker.js?ea88:1 [Intervention] Ignored attempt to cancel a touchend event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.

maybe handleEnd needs

t.cancelable && (t.preventDefault()

like handleStart does?

**Comment by hiyali** [comment]
Thanks for your feedback.

And this issue may be duplicated with [#19](https://github.com/hiyali/vue-smooth-picker/issues/19). So, I'll close this issue for now.

And I upgraded this plugin for this issue based your proposal, you can upgrade it `npm i -S vue-smooth-picker@0.4.2` to the newer version and try again.

Open #19 if the issue still exists.
