### ISSUE TITLE
How to modify rows

### ISSUE THREAD

**Issue by ChristophAtAdlos** [hiyali/vue-smooth-picker#22]
I need to configure vue-smooth-picker to have only 3 rows, 1 upper, the selected and 1 lower.
In addition, the rows should be closer.
Is there a way to configure vue-smooth-picker to fulfill this requirements?

How it is:
![image](https://user-images.githubusercontent.com/29259559/59188184-5d0ccd80-8b77-11e9-801e-cd753d6e47d4.png)

How I like it to be:
![image](https://user-images.githubusercontent.com/29259559/59188330-b248df00-8b77-11e9-9790-3ade8f45f910.png)

**Comment by hiyali** [comment]
@ChristophAtAdlos you can do 3 rows per column, the question duplicates with #11, but closer the rows is hard to do with CSS.

If you wanna do that, you can change the source code.

**Comment by ChristophAtAdlos** [comment]
Ok, thanks for the information!
