### ISSUE TITLE
Issue when using multiple instances in a page

### ISSUE THREAD

**Issue by vowave** [hiyali/vue-smooth-picker#25]
Hey everyone,
There is a problem with this plugin which when you use multiple instance of it in a page second one stops functioning and dragging and all wont work.

**Comment by hiyali** [comment]
@vowave Hi, thank you for this feedback.

I'm hard to say that there are no issues in this situation, I'll take time to confirm this issue exists.
OR you can send a PR to fix this, Thanks a lot.

**Comment by vowave** [comment]
@hiyali I fixed it using resize function.

**Comment by hiyali** [comment]
@vowave Well seems like you are not called the `getGroupsRectList` method in `nextTick(() => {...})` function that after the unstable views became stable.
Like #7 #9 #17
