### ISSUE TITLE
datepicker not working in quasar q-dialog with q-swipe-to-close

### ISSUE THREAD

**Issue by cipto15001** [hiyali/vue-smooth-picker#28]
I'm trying to apply datepicker in quasar bottom sheet. I calendar appear but scrolling not working there

`<q-dialog v-model="lifeplanEditYear" :position="$vssWidth >= 400 ? 'standard' : 'bottom'">
          <q-swipe-to-close v-model="lifeplanEditYear">
            <q-card class="edit-lifeplan-dialog q-pa-md">
              <div class="rectangle-slide"></div>
              <q-card-section>
                <smooth-picker
                  ref="smoothPicker"
                  :data="data"
                  :change="dataChange"
                />
              </q-card-section>
            </q-card>
          </q-swipe-to-close>
        </q-dialog>`

**Comment by cipto15001** [comment]
<q-dialog v-model="lifeplanEditYear" :position="$vssWidth >= 400 ? 'standard' : 'bottom'" style="z-index: 1;">
          <q-swipe-to-close v-model="lifeplanEditYear">
            <q-card class="edit-lifeplan-dialog q-pa-md">
              <div class="rectangle-slide"></div>
              <q-card-section>
                <smooth-picker
                  ref="smoothPicker"
                  :data="data"
                  :change="dataChange"
                />
              </q-card-section>

**Comment by hiyali** [comment]
Hi @cipto15001 , is there a online code show the problem exactly?

**Comment by cipto15001** [comment]
hi @hiyali, if i run code in mobile this code working corectly but when i change to desktop view this picker cannot workting to scroll, when i check in chrome console i can't found error or warning

**Comment by cipto15001** [comment]
`
[Edit .txt](https://github.com/hiyali/vue-smooth-picker/files/4379241/Edit.txt)

`

**Comment by cipto15001** [comment]
Bisa Zidw di w5dv zc di, tt
