### ISSUE TITLE
How to loop scrolling 0 to 9 and 9 to 0 loop . Can i scroll looping ?

### ISSUE THREAD

**Issue by aungchanmyae7315** [hiyali/vue-smooth-picker#30]
https://www.seinlucky123.com/threeD/home?lang=en&wav=20200710.201914

Please check this link.

**Comment by aungchanmyae7315** [comment]
import VuePicker from 'vue-pickers'
      var oneCol = []
      var twoCol = []
      var threeCol = []
  for (let i = 0; i < 10; i++ ) {
     
    oneCol.push({
      label:  i ,
      value: i
    })
     twoCol.push({
      label:   i ,
      value: i
    })
     threeCol.push({
      label:  i ,
      value: i
    })
   
  }


this is my code

**Comment by hiyali** [comment]
Nope. and `'vue-pickers'` is not this component `vue-smooth-picker`.

Thank you.
