### ISSUE TITLE
Vue 3 Update

### ISSUE THREAD

**Issue by jannikbuscha** [hiyali/vue-smooth-picker#48]
Hello,is it possible to update this library to Vue 3?

![image](https://user-images.githubusercontent.com/74017697/127366351-c8a7699a-c15b-4881-87a5-e60c593c6971.png)

**Comment by hiyali** [comment]
Yes, will do this, but can't say any ETA to you

**Comment by jannikbuscha** [comment]
Thank you very much! Take your time 😁
