### ISSUE TITLE
哈喽~我该如何修改他的样式？

### ISSUE THREAD

**Issue by ekkoJ** [hiyali/vue-smooth-picker#5]
我再vue-cli引入之后，用的Less，因为全局修改过Html的font-size，发现你这边也是用的rem，会造成影响，但完全没有找到修改样式的方法

**Comment by hiyali** [comment]
@ekkoJ 你好，这个问题好处理。
1. 不引入 vue-smooth-picker 的 css。
2. 在源码中把 styl 样式提取出来，转换成 less（网上应该有在线转换工具） ，添加到你的项目中参与编译，在这段 less 样式里修改成你要的单位。

你也可以提出更好的方案，合适的话，有机会你我可以把它给实现了。

**Comment by ekkoJ** [comment]
非常感谢~
那我先这么做了~
顺便问一下能否通过Option中的classname直接修改样式或是在Option中加入一个style的对象，能在style中加入能够修改样式的类目？

**Comment by hiyali** [comment]
@ekkoJ 用 className 控制当然可以，style 目前不支持。
