### ISSUE TITLE
无法拖动的情况

### ISSUE THREAD

**Issue by fuiyu** [hiyali/vue-smooth-picker#6]
position:fixed时无法拖动，查看有渲染动作，但没有上移下移变化

**Comment by fuiyu** [comment]
找到发生的条件了，如果组件渲染完毕，picker带的v-show是false的话，在再次变为true时为无法运作

**Comment by hiyali** [comment]
@fuiyu 你好，非常感谢你反馈问题。
刚针对你遇到的问题对组件进行了升级，可以升级到 0.3.3 修复此问题。

**Comment by hiyali** [comment]
@fuiyu 刚解决的有点问题，并且对组件的性能有影响，会尽快针对你提出的问题进行升级，再次感谢。

**Comment by fuiyu** [comment]
哈哈，谢谢你共享的组件

**Comment by hiyali** [comment]
@fuiyu 需要共享 :)
优化了针对此问题的有关逻辑，这次比较彻底。我这边测试通过了。
你可以升级到最新(0.3.6)看一下还有没有问题，没有的话这个issue可以关了。

**Comment by fuiyu** [comment]
好像也是一样无效，只有一开始设置show才能运行，我是嵌在一个隐藏的div里的

**Comment by hiyali** [comment]
@fuiyu 我这次优化的是v-show在此组件上时的情况。 
你的问题可以用
1. 把v-show同时加到组件上。
2. 显示父级层以后，在 Vue.nextTick(() => { ... }) 里做一个 smoothPickerRef. getGroupsRectList() 

来解决。
我再想想，是不是可以利用其他方式优化这种问题。

**Comment by Eamonnzhang** [comment]
这个问题解决了？

**Comment by hiyali** [comment]
@Eamonnzhang 需要手动滞后picker收集拖动区域信息的时间点。
具体是 picker 显示完成后（可以在 `Vue.nextTick(() => { ... })` 里）做 `pickerRef. getGroupsRectList()`
