### ISSUE TITLE
移动端不好用啊

### ISSUE THREAD

**Issue by hgt803** [hiyali/vue-smooth-picker#8]
rem弄得太大了

**Comment by hiyali** [comment]
@hgt803 嘿，你好，感谢你的反馈。
可能是因为你的 html font-size 设置的有点大吧。
如果是按照 16px，picker 大小是刚好合适的。

**Comment by PhoenixMenia** [comment]
对呀，如果移动端的html设置的字体不一样改怎么破？

**Comment by hiyali** [comment]
@PhoenixMenia 看来这个问题是需要解决的，我看能不能近几天把这个问题搞定。

或者如果大家有时间可以按照 [这个PR](https://github.com/hiyali/ng-data-picker/pull/1) 在 vue-smooth-picker 上也提一个 PR，非常感谢。

**Comment by hiyali** [comment]
可以升级 vue-smooth-picker 至 0.3.7 ，用更改picker 的根字体大小来 调整picker整体大小。
