### ISSUE TITLE
datepicker not working in vuetify bottom sheet

### ISSUE THREAD

**Issue by rassemdev** [hiyali/vue-smooth-picker#9]
I'm trying to apply datepicker in vuetify bottom sheet. I calendar appear but scrolling not working there.

**Comment by hiyali** [comment]
@rassemdev Hi there, Thank you for your comment.

You can call pickerInst.[getGroupsRectList()](https://github.com/hiyali/vue-smooth-picker#instance-methods) in Vue.nextTick(() => { here }) after the picker is shown or the container's scrolling done.

Maybe there is a good solution if I can see your code.

**Comment by rassemdev** [comment]
```
<v-bottom-sheet v-model="dobSheet" id="id-dob">
  <v-text-field placeholder="dd-mm-yyyy" slot="activator" v-model="dobVal" prepend-icon="event" readonly></v-text-field>
  <smooth-picker ref="smoothPicker" :data="data" :change="dataChange" />
  <button class="button" type="button" @click="cancel">Cancel</button>
  <button class="button" type="button" @click="confirm">OK</button>
</v-bottom-sheet>
```

In script i just copy paste your datepicker demo code.

**Comment by rassemdev** [comment]
Thanks for your idea, using vue watch solved the problem. i just used this:
watch: {
    dobSheet () {
        this.$nextTick(() => (this.$refs.smoothPicker.getGroupsRectList()))
     }
}

**Comment by hiyali** [comment]
@rassemdev Most welcome, shall we close this issue now?

**Comment by rassemdev** [comment]
Yes, you can close it now. you saved my day.
